### ISSUE TITLE
Removing requirement for proxy server.

### ISSUE THREAD

**Issue by Panoplos** [yatsu/react-apollo-koa-example#1]
I noticed that the only reason this project required `Caddy` was to implement a proxy to the `api` in order to avoid CORS issues, which I thought was a bit overkill (and frankly I wasn't really keen on installing Caddy). This being the case, I modified the project slightly to utilise [kcors](https://github.com/koajs/cors).

Do you agree this is a better (lighter) approach, and if so, would you like me to create a Pull request with my changes?

**Comment by Panoplos** [comment]
Note that I will also be implementing use of [Passport](https://github.com/jaredhanson/passport) for authentication, if you would like me to contribute this ass well.

**Comment by yatsu** [comment]
Yes, I've been using Caddy to run both the dev server and the API server in the same origin.

I changed this to use the dev server's reverse proxy in branch `no-caddy`.

https://github.com/yatsu/react-apollo-koa-example/commit/605c2f9bdbb66c2abfa6d2ca374a28317190b1ef

Now you don't need Caddy and API requests to `localhost:3000` will be redirected to `localhost:7000`.
I checked also WebSocket (Apollo PubSub) and it seems to be working fine.

Enabling CORS is also OK but I think it is not required in a production environment in most cases.
What do you think?

**Comment by yatsu** [comment]
It is also a good idea to use Passport to integrate with auth services.
But I don't know how to do it with Koa2. Let me see your code?

Code contributions are of course welcome!

**Comment by Panoplos** [comment]
Ah, I didn't know about the proxy option for the Node Dev server. Proxy is a decent option. Do you know of this is the recommended practice of the community?

Also, another note, I see you are using `ducks` and `ramda` for functional composition of the reducers. Have you looked at [Recompose](https://github.com/acdlite/recompose)? I think this is the direction many are heading.

**Comment by yatsu** [comment]
The proxy is managed by `react-scripts` and it is described in [create-react-app README](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#proxying-api-requests-in-development).
I think this is the recommended practice of create-react-app community.

I merged `no-caddy` branch to master.

Anyway, thank you for your comments!

**Comment by yatsu** [comment]
Ducks are just file and code organizing rules and they do not affect the actual code.

I use Ramda in reducers.
The current use of Ramda is very simple but it shines when the code grows.
For example, `assocPath()` and lenses are especially useful to access nested objects.

Recompose treats another aspects: composing components.
It is a great idea but I worry that it changes the component code radically,
and I am not sure this is our way to go.

**Comment by yatsu** [comment]
I close this.
