### ISSUE TITLE
No compatible version found: eslint-plugin-flowtype@^2.2.1.0

### ISSUE THREAD

**Issue by Panoplos** [yatsu/react-apollo-koa-example#2]
This was another issue I ran into when first installing. Changing to `eslint-plugin-flowtype@^2.2.1` in `package.json`  fixes it.

**Comment by yatsu** [comment]
Let me check

**Comment by yatsu** [comment]
I upgraded eslint-plugin-flowtype to the latest 2.30.4.
I think it solves the problem.

**Comment by yatsu** [comment]
I found that the latest eslint-plugin-flowtype causes some errors.
I have changed the version to `eslint-plugin-flowtype@^2.2.1` as you said.

Thank you!

**Comment by Panoplos** [comment]
Do you use Atom by any chance? I am trying to debug the koa-passport integration via Nuclide, but seems there are issues with source mapping. Have you run into this issue?

**Comment by yatsu** [comment]
No, I am using Vim in a terminal...

I've upgraded packages and modified `.eslintrc` to avoid some errors today.
Can you execute `yarn` and try it again?

**Comment by Panoplos** [comment]
Yes, fixed. Hey, I have implemented Passport into the stack. Would like to create a branch for you to look at it.

**Comment by yatsu** [comment]
Great!
I am looking forward to see it!

**Comment by Panoplos** [comment]
I need to be added as a contributor to create a branch?

**Comment by Panoplos** [comment]
Also, I have been getting the pre-commit hooks to run all the tests successfully and am down to the last one, which is really throwing me for a loop. It says it expects "React Apollo Koa Example" for the document title of **Home**, but for some reason it is getting "Apollo Koa Example". When I check the `public/index.html` file, it surely has "React Apollo Koa Example" set as the document, but when I check the source in the running app, it is only "Apollo Koa Example"! Where is it getting this from? LOL

**Comment by Panoplos** [comment]
OK, you can see the integration here: https://github.com/Panoplos/react-apollo-koa-passport-example

If you think it is good, I can put in a pull request from the "passport" branch to your repo.

**Comment by yatsu** [comment]
The code looks good. I have not tried it yet though.
Can you create a pull request?

The local sign-in is still possible, right? (because I need it.)

Before merging it, give me some time to closer look at the code and check how it works.

**Comment by Panoplos** [comment]
Local signin is managed by the LocalStrategy object found in Auth. The behaviour is the same as your original implementation. In fact, all the Strategies simply resort to the same behavior, as there is no user management implemented. The only thing that is not implemented is the recent change you made to take the token expiration info from the request data. I will need to look into how to get access to the request when the tokens are created, but I think it should be possible.

**Comment by yatsu** [comment]
OK. I see.

Setting the token expiration from the request header is required for tests. I am currently writing integration tests for token expiration and refresh. I am going to rewrite it to be enabled only in the testing environment.

I am going to run your code.

Thank you!

**Comment by Panoplos** [comment]
Please see that I have added the desired token expiration logic to the pull request.
